# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57e9cee642e0f7631ff0e324b03e075585de1f409db37dba7e0675f8a8cccde9a2cd9c178b7331edf6232a0d8307cc00dcfb42d5caac188feced49230ad1781a

test:
  secret_key_base: 3ab6987202f4a08969d074a9a87ae12ae337f5d5395ceafc0e8930d345a9f15610d46777d3ac014d031508770dfe9ecf383936fa3dec1e90e0d26a85cac01856

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
